// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Travether.Api.Data;

#nullable disable

namespace Travether.Api.Data.Migrations
{
    [DbContext(typeof(TravetherDbContext))]
    [Migration("20261006200219_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Travether.Api.Domain.ActivityPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("audience");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<string>("DestinationPrecision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("destination_precision");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<Point>("Origin")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginAreaLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("origin_area_label");

                    b.Property<Point>("OriginPublic")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("origin_public")
                        .HasComputedColumnSql("ST_SnapToGrid(origin::geometry, 0.01)::geography", true);

                    b.Property<string>("Purpose")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("purpose");

                    b.Property<int>("SeatLimit")
                        .HasColumnType("integer")
                        .HasColumnName("seat_limit");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_activity_plans");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_activity_plans_card_id");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_activity_plans_host_id");

                    b.HasIndex("OriginPublic")
                        .HasDatabaseName("ix_activity_plans_origin_public");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OriginPublic"), "gist");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_activity_plans_starts_at");

                    b.ToTable("activity_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_activity_plans_audience", "audience IN ('open', 'groups_only')");

                            t.HasCheckConstraint("ck_activity_plans_category", "category IN ('hike', 'day_trip', 'food', 'nightlife', 'tour', 'beach', 'transport', 'other')");

                            t.HasCheckConstraint("ck_activity_plans_destination_precision", "destination_precision IN ('exact', 'regional')");

                            t.HasCheckConstraint("ck_activity_plans_seat_limit", "seat_limit BETWEEN 2 AND 100");

                            t.HasCheckConstraint("ck_activity_plans_status", "status IN ('open', 'full', 'cancelled', 'done')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.Block", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("BlockerId", "BlockedId")
                        .HasName("pk_blocks");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_blocks_blocked_id");

                    b.ToTable("blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_blocks_not_self", "blocker_id <> blocked_id");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.CardMember", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("CardId", "UserId")
                        .HasName("pk_card_members");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasDatabaseName("ux_card_members_one_owner")
                        .HasFilter("role = 'owner'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_members_user_id");

                    b.ToTable("card_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_card_members_role", "role IN ('owner', 'co_admin', 'member')");

                            t.HasCheckConstraint("ck_card_members_status", "status IN ('active', 'left', 'removed')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.CardRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_card_requests");

                    b.HasIndex("DecidedById")
                        .HasDatabaseName("ix_card_requests_decided_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_requests_user_id");

                    b.HasIndex("CardId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_card_requests_card_id_user_id")
                        .HasFilter("status = 'requested'");

                    b.ToTable("card_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_card_requests_status", "status IN ('requested', 'approved', 'rejected', 'withdrawn', 'expired')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_consents");

                    b.HasIndex("UserId", "Kind")
                        .HasDatabaseName("ix_consents_user_id_kind");

                    b.ToTable("consents", null, t =>
                        {
                            t.HasCheckConstraint("ck_consents_kind", "kind IN ('terms', 'privacy_policy', 'community_guidelines', 'marketing_email')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("Type", "RefId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_type_ref_id")
                        .HasFilter("ref_id IS NOT NULL");

                    b.ToTable("conversations", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversations_ref", "(type = 'direct') = (ref_id IS NULL)");

                            t.HasCheckConstraint("ck_conversations_type", "type IN ('card', 'plan', 'direct')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("pk_conversation_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversation_members_user_id");

                    b.ToTable("conversation_members", (string)null);
                });

            modelBuilder.Entity("Travether.Api.Domain.MeetConfirmation", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlanId", "UserId")
                        .HasName("pk_meet_confirmations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_meet_confirmations_user_id");

                    b.ToTable("meet_confirmations", null, t =>
                        {
                            t.HasCheckConstraint("ck_meet_confirmations_answer", "answer IN ('met', 'cancelled', 'no_show')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_conversation_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Travether.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Travether.Api.Domain.PlanParticipant", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("SourceCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_card_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("PlanId", "UserId")
                        .HasName("pk_plan_participants");

                    b.HasIndex("SourceCardId")
                        .HasDatabaseName("ix_plan_participants_source_card_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_plan_participants_user_id");

                    b.ToTable("plan_participants", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_participants_status", "status IN ('active', 'left', 'removed')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.PlanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("message");

                    b.PrimitiveCollection<List<Guid>>("PartyUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("party_user_ids");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<Guid?>("SourceCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_card_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_plan_requests");

                    b.HasIndex("DecidedById")
                        .HasDatabaseName("ix_plan_requests_decided_by_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_plan_requests_requester_id");

                    b.HasIndex("SourceCardId")
                        .HasDatabaseName("ix_plan_requests_source_card_id");

                    b.HasIndex("PlanId", "RequesterId")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_requests_plan_id_requester_id")
                        .HasFilter("status = 'requested'");

                    b.ToTable("plan_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_requests_status", "status IN ('requested', 'approved', 'rejected', 'withdrawn', 'expired')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Travether.Api.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedById")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_reports_reporter_id");

                    b.HasIndex("ResolvedById")
                        .HasDatabaseName("ix_reports_resolved_by_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_reports_status_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_reports_target_type_target_id");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_status", "status IN ('open', 'actioned', 'dismissed')");

                            t.HasCheckConstraint("ck_reports_target_type", "target_type IN ('user', 'card', 'plan', 'message', 'review')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("RepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replied_at");

                    b.Property<string>("ReplyText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reply_text");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("RevieweeId")
                        .HasDatabaseName("ix_reviews_reviewee_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_reviews_reviewer_id");

                    b.HasIndex("PlanId", "ReviewerId", "RevieweeId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_plan_id_reviewer_id_reviewee_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_not_self", "reviewer_id <> reviewee_id");

                            t.HasCheckConstraint("ck_reviews_stars", "stars BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.PrimitiveCollection<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("VerificationBadges")
                        .HasColumnType("integer")
                        .HasColumnName("verification_badges");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_country_code", "country_code ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_users_email_lower", "email = lower(email)");

                            t.HasCheckConstraint("ck_users_role", "role IN ('traveler', 'moderator')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.VacationCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.PrimitiveCollection<List<string>>("Regions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("regions");

                    b.Property<string>("ShareSlug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("share_slug");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_vacation_cards");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vacation_cards_owner_id");

                    b.HasIndex("ShareSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_vacation_cards_share_slug");

                    b.ToTable("vacation_cards", null, t =>
                        {
                            t.HasCheckConstraint("ck_vacation_cards_country_code", "country_code ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_vacation_cards_dates", "ends_on >= starts_on");

                            t.HasCheckConstraint("ck_vacation_cards_regions", "cardinality(regions) >= 1");

                            t.HasCheckConstraint("ck_vacation_cards_visibility", "visibility IN ('public', 'invite_only')");
                        });
                });

            modelBuilder.Entity("Travether.Api.Domain.ActivityPlan", b =>
                {
                    b.HasOne("Travether.Api.Domain.VacationCard", "Card")
                        .WithMany("Plans")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_plans_vacation_cards_card_id");

                    b.HasOne("Travether.Api.Domain.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_plans_users_host_id");

                    b.Navigation("Card");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Travether.Api.Domain.Block", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_users_blocked_id");

                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_users_blocker_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.CardMember", b =>
                {
                    b.HasOne("Travether.Api.Domain.VacationCard", "Card")
                        .WithMany("Members")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_members_vacation_cards_card_id");

                    b.HasOne("Travether.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_members_users_user_id");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travether.Api.Domain.CardRequest", b =>
                {
                    b.HasOne("Travether.Api.Domain.VacationCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_requests_vacation_cards_card_id");

                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_card_requests_users_decided_by_id");

                    b.HasOne("Travether.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_requests_users_user_id");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travether.Api.Domain.Consent", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consents_users_user_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.ConversationMember", b =>
                {
                    b.HasOne("Travether.Api.Domain.Conversation", null)
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_members_conversations_conversation_id");

                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_members_users_user_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.MeetConfirmation", b =>
                {
                    b.HasOne("Travether.Api.Domain.ActivityPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meet_confirmations_activity_plans_plan_id");

                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meet_confirmations_users_user_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.Message", b =>
                {
                    b.HasOne("Travether.Api.Domain.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("Travether.Api.Domain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_id");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Travether.Api.Domain.Notification", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.PlanParticipant", b =>
                {
                    b.HasOne("Travether.Api.Domain.ActivityPlan", "Plan")
                        .WithMany("Participants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_participants_activity_plans_plan_id");

                    b.HasOne("Travether.Api.Domain.VacationCard", null)
                        .WithMany()
                        .HasForeignKey("SourceCardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plan_participants_vacation_cards_source_card_id");

                    b.HasOne("Travether.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_participants_users_user_id");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travether.Api.Domain.PlanRequest", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plan_requests_users_decided_by_id");

                    b.HasOne("Travether.Api.Domain.ActivityPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_requests_activity_plans_plan_id");

                    b.HasOne("Travether.Api.Domain.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_requests_users_requester_id");

                    b.HasOne("Travether.Api.Domain.VacationCard", null)
                        .WithMany()
                        .HasForeignKey("SourceCardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plan_requests_vacation_cards_source_card_id");

                    b.Navigation("Plan");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Travether.Api.Domain.PushSubscription", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.Report", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reporter_id");

                    b.HasOne("Travether.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_users_resolved_by_id");
                });

            modelBuilder.Entity("Travether.Api.Domain.Review", b =>
                {
                    b.HasOne("Travether.Api.Domain.ActivityPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_activity_plans_plan_id");

                    b.HasOne("Travether.Api.Domain.User", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_reviewee_id");

                    b.HasOne("Travether.Api.Domain.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_reviewer_id");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Travether.Api.Domain.VacationCard", b =>
                {
                    b.HasOne("Travether.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vacation_cards_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Travether.Api.Domain.ActivityPlan", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Travether.Api.Domain.Conversation", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Travether.Api.Domain.VacationCard", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
